### ISSUE TITLE
What is this app?

### ISSUE THREAD

**Issue by plutonium-239** [LeronArenwino/Namarie#1]
Hello
Is the purpose of this app to be a desktop music player or is it like the site [jukebox.today](https://jukebox.today/)?

**Comment by fduenasc** [comment]
It is a desktop jukebox app, but this work with local files. I'm trying to implement YouTube videos, but now I'm working, so I don't have time to do it at now.

The app show a list of music with song's number, then you can select a song using song's number or up—down keys, and it will play. If the file is a video, the app shows it.
